"""
A script to execute labelme command in batch.
When there are many labelme json files need to be converted to
actual labels, this script can execute labelme command in batch efficiently.
Make sure to install labelme on the system first.

Parameters need change:
1) path
"""
import os

path = "C:/imecdata/training_set/May17"  # A path of a folder which contains multiple Json files generated by labelme tool.
# This script enables multiple json files to be converted at the same time.
dirs = os.listdir(path)
os.chdir(path)
for item in dirs:
    print(item)
    if item.endswith(".json"):
        os.system("labelme_json_to_dataset " + item + " -o " + item.split(".")[0])